// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzGEf3F9LX3TLPLt3iuKITlev_u2FOzTQ',
    appId: '1:275612905612:web:76fa85fc0acf0acaf8cba9',
    messagingSenderId: '275612905612',
    projectId: 'push-notifications-reading-app',
    authDomain: 'push-notifications-reading-app.firebaseapp.com',
    storageBucket: 'push-notifications-reading-app.firebasestorage.app',
    measurementId: 'G-LZG510HS3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk3wVvDPmhIf5Ww3Zi-VlE9yX3mJr2E4M',
    appId: '1:275612905612:android:a912238aba24beabf8cba9',
    messagingSenderId: '275612905612',
    projectId: 'push-notifications-reading-app',
    storageBucket: 'push-notifications-reading-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCED11CQxx0szm5EWHykxKNDXALPFjwxew',
    appId: '1:275612905612:ios:43a60f2ba149c492f8cba9',
    messagingSenderId: '275612905612',
    projectId: 'push-notifications-reading-app',
    storageBucket: 'push-notifications-reading-app.firebasestorage.app',
    iosBundleId: 'com.example.readingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCED11CQxx0szm5EWHykxKNDXALPFjwxew',
    appId: '1:275612905612:ios:43a60f2ba149c492f8cba9',
    messagingSenderId: '275612905612',
    projectId: 'push-notifications-reading-app',
    storageBucket: 'push-notifications-reading-app.firebasestorage.app',
    iosBundleId: 'com.example.readingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzGEf3F9LX3TLPLt3iuKITlev_u2FOzTQ',
    appId: '1:275612905612:web:ee4d193aff08eff6f8cba9',
    messagingSenderId: '275612905612',
    projectId: 'push-notifications-reading-app',
    authDomain: 'push-notifications-reading-app.firebaseapp.com',
    storageBucket: 'push-notifications-reading-app.firebasestorage.app',
    measurementId: 'G-QZ3DRYFX9C',
  );
}
