import 'package:reading_app/features/shared/models/book.dart';

final List<BookModel> dummyBook = [
  BookModel(
    id: 0,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    isFavourite: false,
    isInLibrary: false,
    coverImage: '',
  ),
  BookModel(
    id: 0,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    isFavourite: false,
    isInLibrary: false,
    coverImage: '',
  ),
  BookModel(
    id: 0,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    isFavourite: false,
    isInLibrary: false,
    coverImage: '',
  ),
  BookModel(
    id: 0,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    isFavourite: false,
    isInLibrary: false,
    coverImage: '',
  ),BookModel(
    id: 0,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    isFavourite: false,
    isInLibrary: false,
    coverImage: '',
  ),
];
