import 'package:reading_app/features/shared/models/book.dart';

final List<BookModel> dummyBook = [
  BookModel(
    id: 1110,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    coverImage: '',
    points: 0,
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    progress: 0,
    isFavourite: false,
    isChallenged: false,
    isInLibrary: false,
  ),
  BookModel(
    id: 190,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    coverImage: '',
    points: 0,
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    progress: 0,
    isFavourite: false,
    isChallenged: false,
    isInLibrary: false,
  ),
  BookModel(
    id: 210,
    title: '',
    description: '',
    authorName: '',
    countryFlag: '',
    publishDate: '',
    coverImage: '',
    points: 0,
    starRate: 0,
    readersCount: 0,
    categoryName: '',
    sizeCategoryName: '',
    numberOfPages: 0,
    progress: 0,
    isFavourite: false,
    isChallenged: false,
    isInLibrary: false,
  ),

];
